[package]
name = "my_csvpn_pinger"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
dotenv = "0.15.0"
colored = "2.1.0"
anyhow = "1.0.93"
tracing = "0.1.40"
env_logger = "0.11.5"